printStarting("CREATING VEHICLE DOOR LIST")
VehicleDoor.create!(name: "2 Door")
VehicleDoor.create!(name: "3 Door")
VehicleDoor.create!(name: "4 Door")
VehicleDoor.create!(name: "5 Door")
VehicleDoor.create!(name: "6 Door")
printFinished()

printStarting("CREATING VEHICLE SIZE LIST")
VehicleSize.create!(name: "Small")
VehicleSize.create!(name: "Large")
printFinished()

printStarting("CREATING VEHICLE TYPE LIST")
VehicleType.create!(name: "Pickup")
VehicleType.create!(name: "SUV/Crossover")
VehicleType.create!(name: "SUV")
VehicleType.create!(name: "Crossover")
VehicleType.create!(name: "CUV")
VehicleType.create!(name: "Van")
VehicleType.create!(name: "Minivan")
VehicleType.create!(name: "Convertible")
VehicleType.create!(name: "Coupe")
VehicleType.create!(name: "Sedan")
VehicleType.create!(name: "Wagon")
VehicleType.create!(name: "Hatchback")
VehicleType.create!(name: "Pickup 5 1/2 ft bed")
VehicleType.create!(name: "Pickup 5 ft bed")
VehicleType.create!(name: "Pickup 6 1/3 ft bed")
VehicleType.create!(name: "Pickup 6 ft bed")
VehicleType.create!(name: "Pickup 8 ft bed")
VehicleType.create!(name: "Pickup-Long Bed")
VehicleType.create!(name: "Pickup-Short Bed")
VehicleType.create!(name: "Roadster")
VehicleType.create!(name: "SUV/Crossover/Pickup")
VehicleType.create!(name: "SUV/Crossover/Pickup 5 1/4 ft bed")
VehicleType.create!(name: "Van/Minivan")

printFinished()

printStarting("CREATING VEHICLE YEAR LIST")

VehicleYear.create!(name: "2019")
VehicleYear.create!(name: "2018")
VehicleYear.create!(name: "2017")
VehicleYear.create!(name: "2016")
VehicleYear.create!(name: "2015")
VehicleYear.create!(name: "2014")
VehicleYear.create!(name: "2013")
VehicleYear.create!(name: "2012")
VehicleYear.create!(name: "2011")
VehicleYear.create!(name: "2010")

VehicleYear.create!(name: "2009")
VehicleYear.create!(name: "2008")
VehicleYear.create!(name: "2007")
VehicleYear.create!(name: "2006")
VehicleYear.create!(name: "2005")
VehicleYear.create!(name: "2004")
VehicleYear.create!(name: "2003")
VehicleYear.create!(name: "2002")
VehicleYear.create!(name: "2001")
VehicleYear.create!(name: "2000")

VehicleYear.create!(name: "1999")
VehicleYear.create!(name: "1998")
VehicleYear.create!(name: "1997")
VehicleYear.create!(name: "1996")
VehicleYear.create!(name: "1995")
VehicleYear.create!(name: "1994")
VehicleYear.create!(name: "1993")
VehicleYear.create!(name: "1992")
VehicleYear.create!(name: "1991")
VehicleYear.create!(name: "1990")

VehicleYear.create!(name: "1989")
VehicleYear.create!(name: "1988")
VehicleYear.create!(name: "1987")
VehicleYear.create!(name: "1986")
VehicleYear.create!(name: "1985")
VehicleYear.create!(name: "1984")
VehicleYear.create!(name: "1983")
VehicleYear.create!(name: "1982")
VehicleYear.create!(name: "1981")
VehicleYear.create!(name: "1980")

VehicleYear.create!(name: "1979")
VehicleYear.create!(name: "1978")
VehicleYear.create!(name: "1977")
VehicleYear.create!(name: "1976")
VehicleYear.create!(name: "1975")
VehicleYear.create!(name: "1974")
VehicleYear.create!(name: "1973")
VehicleYear.create!(name: "1972")
VehicleYear.create!(name: "1971")
VehicleYear.create!(name: "1970")

VehicleYear.create!(name: "1969")
VehicleYear.create!(name: "1968")
VehicleYear.create!(name: "1967")
VehicleYear.create!(name: "1966")
VehicleYear.create!(name: "1965")
VehicleYear.create!(name: "1964")
VehicleYear.create!(name: "1963")
VehicleYear.create!(name: "1962")
VehicleYear.create!(name: "1961")
VehicleYear.create!(name: "1960")

VehicleYear.create!(name: "1959")
VehicleYear.create!(name: "1958")
VehicleYear.create!(name: "1957")
VehicleYear.create!(name: "1956")
VehicleYear.create!(name: "1955")
VehicleYear.create!(name: "1954")
VehicleYear.create!(name: "1953")
VehicleYear.create!(name: "1952")
VehicleYear.create!(name: "1951")
VehicleYear.create!(name: "1950")

VehicleYear.create!(name: "1949")
VehicleYear.create!(name: "1948")
VehicleYear.create!(name: "1947")
VehicleYear.create!(name: "1946")
VehicleYear.create!(name: "1945")
VehicleYear.create!(name: "1944")
VehicleYear.create!(name: "1943")
VehicleYear.create!(name: "1942")
VehicleYear.create!(name: "1941")
VehicleYear.create!(name: "1940")

VehicleYear.create!(name: "1939")
VehicleYear.create!(name: "1938")
VehicleYear.create!(name: "1937")
VehicleYear.create!(name: "1936")
VehicleYear.create!(name: "1935")
VehicleYear.create!(name: "1934")
VehicleYear.create!(name: "1933")
VehicleYear.create!(name: "1932")
VehicleYear.create!(name: "1931")
VehicleYear.create!(name: "1930")

VehicleYear.create!(name: "1929")
VehicleYear.create!(name: "1928")
VehicleYear.create!(name: "1927")
VehicleYear.create!(name: "1926")
VehicleYear.create!(name: "1925")
VehicleYear.create!(name: "1924")
VehicleYear.create!(name: "1923")
VehicleYear.create!(name: "1922")
VehicleYear.create!(name: "1921")
VehicleYear.create!(name: "1920")

VehicleYear.create!(name: "1919")
VehicleYear.create!(name: "1918")
VehicleYear.create!(name: "1917")
VehicleYear.create!(name: "1916")
VehicleYear.create!(name: "1915")
VehicleYear.create!(name: "1914")
VehicleYear.create!(name: "1913")
VehicleYear.create!(name: "1912")
VehicleYear.create!(name: "1911")
VehicleYear.create!(name: "1910")

VehicleYear.create!(name: "1909")
VehicleYear.create!(name: "1908")
VehicleYear.create!(name: "1907")
VehicleYear.create!(name: "1906")
VehicleYear.create!(name: "1905")
VehicleYear.create!(name: "1904")
VehicleYear.create!(name: "1903")
VehicleYear.create!(name: "1902")
VehicleYear.create!(name: "1901")
VehicleYear.create!(name: "1900")

printFinished()


