
dev_realm:            9c17bbebb26acb4312b9f44bdd579bd85b20
dev_key:              qyprdFtG87sAeEwyFLmiouPZs77bAA
dev_secret:           WwtTDXPP5WjhnrepdLH5NcnSEvNLjQepoHR45vsw
access_token:         qyprdwpTnFocUlV5g2En2ivyP9fDujoGQf88mvw1o0k54mG6
access_token_secret:  la4r4B6yB5UkFz0fNiUFv7M4DqUZEsVG2bNUIaRI


prod_key: qyprdFtG87sAeEwyFLmiouPZs77bAA
prod_secret: WwtTDXPP5WjhnrepdLH5NcnSEvNLjQepoHR45vsw
access_token: 9c17bbebb26acb4312b9f44bdd579bd85b20



