# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf59a1816f6b73f401f2bfd0317fa243e132871f44f71af04fb16b07f86d97bfe22ca40695f86fb03b1d87f8414017183c47225ab6a7e6b183020e90f63124b8

  gb_realm:           <%= ENV["SW_QB_REALM"] %>
  qb_consumer_key:    <%= ENV["SW_QB_CONSUMER_KEY"] %>
  qb_consumer_secret: <%= ENV["SW_QB_CONSUMER_SECRET"] %>

  qb_access_token:    <%= ENV["SW_QB_ACCESS_TOKEN"] %>
  qb_token_secret:    <%= ENV["SW_QB_TOKEN_SECRET"] %>

test:
  secret_key_base: 196bf92f72c6592d3ed7a507150fb2158ffdeb3401daedd26e631d6f5fd89d431131e581030f65296f6433cd3809b8ee6246379ca1823a3d9186ee3962229b70

  gb_realm:           <%= ENV["SW_QB_REALM"] %>
  qb_consumer_key:    <%= ENV["SW_QB_CONSUMER_KEY"] %>
  qb_consumer_secret: <%= ENV["SW_QB_CONSUMER_SECRET"] %>

  qb_access_token:    <%= ENV["SW_QB_ACCESS_TOKEN"] %>
  qb_token_secret:    <%= ENV["SW_QB_TOKEN_SECRET"] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:    <%= ENV["SECRET_KEY_BASE"] %>

  gb_realm:           <%= ENV["QB_REALM"] %>
  qb_consumer_key:    <%= ENV["QB_CONSUMER_KEY"] %>
  qb_consumer_secret: <%= ENV["QB_CONSUMER_SECRET"] %>

  qb_access_token:    <%= ENV["QB_ACCESS_TOKEN"] %>
  qb_token_secret:    <%= ENV["QB_TOKEN_SECRET"] %>

