# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf59a1816f6b73f401f2bfd0317fa243e132871f44f71af04fb16b07f86d97bfe22ca40695f86fb03b1d87f8414017183c47225ab6a7e6b183020e90f63124b8

  admin_email:     <%= ENV["DEV_ADMIN_EMAIL"] %>
  admin_username:  <%= ENV["DEV_ADMIN_USERNAME"] %>
  admin_password:  <%= ENV["DEV_ADMIN_PASSWORD"] %>

  user_email:       <%= ENV["DEV_USER_EMAIL"] %>
  user_username:    <%= ENV["DEV_USER_USERNAME"] %>
  user_password:    <%= ENV["DEV_USER_PASSWORD"] %>
  user_last_name:   <%= ENV["DEV_USER_LAST_NAME"] %>
  user_first_name:  <%= ENV["DEV_USER_FIRST_NAME"] %>
  user_salutation:  <%= ENV["DEV_USER_SALUTATION"] %>
  user_street1:     <%= ENV["DEV_USER_STREET1"] %>
  user_city:        <%= ENV["DEV_USER_CITY"] %>
  user_state:       <%= ENV["DEV_USER_STATE"] %>
  user_zip:         <%= ENV["DEV_USER_ZIP"] %>
  user_mobile:      <%= ENV["DEV_USER_MOBILE"] %>
  user_phone1:      <%= ENV["DEV_USER_PHONE1"] %>

  gb_realm:           <%= ENV["SW_QB_REALM"] %>
  qb_consumer_key:    <%= ENV["SW_QB_CONSUMER_KEY"] %>
  qb_consumer_secret: <%= ENV["SW_QB_CONSUMER_SECRET"] %>

  qb_access_token:    <%= ENV["SW_QB_ACCESS_TOKEN"] %>
  qb_token_secret:    <%= ENV["SW_QB_TOKEN_SECRET"] %>

  fb_app_id:      <%= ENV["SW_FB_APP_ID"] %>
  fb_app_secret:  <%= ENV["SW_FB_APP_SECRET"] %>

  bt_merchant_id: <%= ENV["BT_MERCHANT_ID"] %>
  bt_public_key:  <%= ENV["BT_PUBLIC_KEY"] %>
  bt_private_key: <%= ENV["BT_PRIVATE_KEY"] %>

test:
  secret_key_base: 196bf92f72c6592d3ed7a507150fb2158ffdeb3401daedd26e631d6f5fd89d431131e581030f65296f6433cd3809b8ee6246379ca1823a3d9186ee3962229b70

  gb_realm:           <%= ENV["SW_QB_REALM"] %>
  qb_consumer_key:    <%= ENV["SW_QB_CONSUMER_KEY"] %>
  qb_consumer_secret: <%= ENV["SW_QB_CONSUMER_SECRET"] %>

  qb_access_token:    <%= ENV["SW_QB_ACCESS_TOKEN"] %>
  qb_token_secret:    <%= ENV["SW_QB_TOKEN_SECRET"] %>

  fb_app_id:      <%= ENV["SW_FB_APP_ID"] %>
  fb_app_secret:  <%= ENV["SW_FB_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  admin_email:     <%= ENV["ADMIN_EMAIL"] %>
  admin_username:  <%= ENV["ADMIN_USERNAME"] %>
  admin_password:  <%= ENV["ADMIN_PASSWORD"] %>

  user_email:       <%= ENV["USER_EMAIL"] %>
  user_username:    <%= ENV["USER_USERNAME"] %>
  user_password:    <%= ENV["USER_PASSWORD"] %>
  user_last_name:   <%= ENV["USER_LAST_NAME"] %>
  user_first_name:  <%= ENV["USER_FIRST_NAME"] %>
  user_salutation:  <%= ENV["USER_SALUTATION"] %>
  user_street1:     <%= ENV["USER_STREET1"] %>
  user_city:        <%= ENV["USER_CITY"] %>
  user_state:       <%= ENV["USER_STATE"] %>
  user_zip:         <%= ENV["USER_ZIP"] %>
  user_mobile:      <%= ENV["USER_MOBILE"] %>
  user_phone1:      <%= ENV["USER_PHONE1"] %>

  gb_realm:           <%= ENV["QB_REALM"] %>
  qb_consumer_key:    <%= ENV["QB_CONSUMER_KEY"] %>
  qb_consumer_secret: <%= ENV["QB_CONSUMER_SECRET"] %>

  qb_access_token: <%= ENV["QB_ACCESS_TOKEN"] %>
  qb_token_secret: <%= ENV["QB_TOKEN_SECRET"] %>

  fb_app_id:      <%= ENV["SW_FB_APP_ID"] %>
  fb_app_secret:  <%= ENV["SW_FB_APP_SECRET"] %>

