require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Customers::DashboardsController do

  # This should return the minimal set of attributes required to create a valid
  # Customers::Dashboard. As you add validations to Customers::Dashboard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "index" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Customers::DashboardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all customers_dashboards as @customers_dashboards" do
      dashboard = Customers::Dashboard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:customers_dashboards).should eq([dashboard])
    end
  end

  describe "GET show" do
    it "assigns the requested customers_dashboard as @customers_dashboard" do
      dashboard = Customers::Dashboard.create! valid_attributes
      get :show, {:id => dashboard.to_param}, valid_session
      assigns(:customers_dashboard).should eq(dashboard)
    end
  end

  describe "GET new" do
    it "assigns a new customers_dashboard as @customers_dashboard" do
      get :new, {}, valid_session
      assigns(:customers_dashboard).should be_a_new(Customers::Dashboard)
    end
  end

  describe "GET edit" do
    it "assigns the requested customers_dashboard as @customers_dashboard" do
      dashboard = Customers::Dashboard.create! valid_attributes
      get :edit, {:id => dashboard.to_param}, valid_session
      assigns(:customers_dashboard).should eq(dashboard)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Customers::Dashboard" do
        expect {
          post :create, {:customers_dashboard => valid_attributes}, valid_session
        }.to change(Customers::Dashboard, :count).by(1)
      end

      it "assigns a newly created customers_dashboard as @customers_dashboard" do
        post :create, {:customers_dashboard => valid_attributes}, valid_session
        assigns(:customers_dashboard).should be_a(Customers::Dashboard)
        assigns(:customers_dashboard).should be_persisted
      end

      it "redirects to the created customers_dashboard" do
        post :create, {:customers_dashboard => valid_attributes}, valid_session
        response.should redirect_to(Customers::Dashboard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved customers_dashboard as @customers_dashboard" do
        # Trigger the behavior that occurs when invalid params are submitted
        Customers::Dashboard.any_instance.stub(:save).and_return(false)
        post :create, {:customers_dashboard => { "index" => "invalid value" }}, valid_session
        assigns(:customers_dashboard).should be_a_new(Customers::Dashboard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Customers::Dashboard.any_instance.stub(:save).and_return(false)
        post :create, {:customers_dashboard => { "index" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested customers_dashboard" do
        dashboard = Customers::Dashboard.create! valid_attributes
        # Assuming there are no other customers_dashboards in the database, this
        # specifies that the Customers::Dashboard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Customers::Dashboard.any_instance.should_receive(:update_attributes).with({ "index" => "MyString" })
        put :update, {:id => dashboard.to_param, :customers_dashboard => { "index" => "MyString" }}, valid_session
      end

      it "assigns the requested customers_dashboard as @customers_dashboard" do
        dashboard = Customers::Dashboard.create! valid_attributes
        put :update, {:id => dashboard.to_param, :customers_dashboard => valid_attributes}, valid_session
        assigns(:customers_dashboard).should eq(dashboard)
      end

      it "redirects to the customers_dashboard" do
        dashboard = Customers::Dashboard.create! valid_attributes
        put :update, {:id => dashboard.to_param, :customers_dashboard => valid_attributes}, valid_session
        response.should redirect_to(dashboard)
      end
    end

    describe "with invalid params" do
      it "assigns the customers_dashboard as @customers_dashboard" do
        dashboard = Customers::Dashboard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Customers::Dashboard.any_instance.stub(:save).and_return(false)
        put :update, {:id => dashboard.to_param, :customers_dashboard => { "index" => "invalid value" }}, valid_session
        assigns(:customers_dashboard).should eq(dashboard)
      end

      it "re-renders the 'edit' template" do
        dashboard = Customers::Dashboard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Customers::Dashboard.any_instance.stub(:save).and_return(false)
        put :update, {:id => dashboard.to_param, :customers_dashboard => { "index" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested customers_dashboard" do
      dashboard = Customers::Dashboard.create! valid_attributes
      expect {
        delete :destroy, {:id => dashboard.to_param}, valid_session
      }.to change(Customers::Dashboard, :count).by(-1)
    end

    it "redirects to the customers_dashboards list" do
      dashboard = Customers::Dashboard.create! valid_attributes
      delete :destroy, {:id => dashboard.to_param}, valid_session
      response.should redirect_to(customers_dashboards_url)
    end
  end

end
