require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Dashboard::AppointmentsController do

  # This should return the minimal set of attributes required to create a valid
  # Dashboard::Appointment. As you add validations to Dashboard::Appointment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Dashboard::AppointmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dashboard_appointments as @dashboard_appointments" do
      appointment = Dashboard::Appointment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dashboard_appointments).should eq([appointment])
    end
  end

  describe "GET show" do
    it "assigns the requested dashboard_appointment as @dashboard_appointment" do
      appointment = Dashboard::Appointment.create! valid_attributes
      get :show, {:id => appointment.to_param}, valid_session
      assigns(:dashboard_appointment).should eq(appointment)
    end
  end

  describe "GET new" do
    it "assigns a new dashboard_appointment as @dashboard_appointment" do
      get :new, {}, valid_session
      assigns(:dashboard_appointment).should be_a_new(Dashboard::Appointment)
    end
  end

  describe "GET edit" do
    it "assigns the requested dashboard_appointment as @dashboard_appointment" do
      appointment = Dashboard::Appointment.create! valid_attributes
      get :edit, {:id => appointment.to_param}, valid_session
      assigns(:dashboard_appointment).should eq(appointment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dashboard::Appointment" do
        expect {
          post :create, {:dashboard_appointment => valid_attributes}, valid_session
        }.to change(Dashboard::Appointment, :count).by(1)
      end

      it "assigns a newly created dashboard_appointment as @dashboard_appointment" do
        post :create, {:dashboard_appointment => valid_attributes}, valid_session
        assigns(:dashboard_appointment).should be_a(Dashboard::Appointment)
        assigns(:dashboard_appointment).should be_persisted
      end

      it "redirects to the created dashboard_appointment" do
        post :create, {:dashboard_appointment => valid_attributes}, valid_session
        response.should redirect_to(Dashboard::Appointment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dashboard_appointment as @dashboard_appointment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dashboard::Appointment.any_instance.stub(:save).and_return(false)
        post :create, {:dashboard_appointment => {  }}, valid_session
        assigns(:dashboard_appointment).should be_a_new(Dashboard::Appointment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dashboard::Appointment.any_instance.stub(:save).and_return(false)
        post :create, {:dashboard_appointment => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dashboard_appointment" do
        appointment = Dashboard::Appointment.create! valid_attributes
        # Assuming there are no other dashboard_appointments in the database, this
        # specifies that the Dashboard::Appointment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dashboard::Appointment.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => appointment.to_param, :dashboard_appointment => { "these" => "params" }}, valid_session
      end

      it "assigns the requested dashboard_appointment as @dashboard_appointment" do
        appointment = Dashboard::Appointment.create! valid_attributes
        put :update, {:id => appointment.to_param, :dashboard_appointment => valid_attributes}, valid_session
        assigns(:dashboard_appointment).should eq(appointment)
      end

      it "redirects to the dashboard_appointment" do
        appointment = Dashboard::Appointment.create! valid_attributes
        put :update, {:id => appointment.to_param, :dashboard_appointment => valid_attributes}, valid_session
        response.should redirect_to(appointment)
      end
    end

    describe "with invalid params" do
      it "assigns the dashboard_appointment as @dashboard_appointment" do
        appointment = Dashboard::Appointment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dashboard::Appointment.any_instance.stub(:save).and_return(false)
        put :update, {:id => appointment.to_param, :dashboard_appointment => {  }}, valid_session
        assigns(:dashboard_appointment).should eq(appointment)
      end

      it "re-renders the 'edit' template" do
        appointment = Dashboard::Appointment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dashboard::Appointment.any_instance.stub(:save).and_return(false)
        put :update, {:id => appointment.to_param, :dashboard_appointment => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dashboard_appointment" do
      appointment = Dashboard::Appointment.create! valid_attributes
      expect {
        delete :destroy, {:id => appointment.to_param}, valid_session
      }.to change(Dashboard::Appointment, :count).by(-1)
    end

    it "redirects to the dashboard_appointments list" do
      appointment = Dashboard::Appointment.create! valid_attributes
      delete :destroy, {:id => appointment.to_param}, valid_session
      response.should redirect_to(dashboard_appointments_url)
    end
  end

end
