printStarting("CREATING VEHICLE DOOR LIST")
VehicleDoor.create!(name: "2 Door")
VehicleDoor.create!(name: "3 Door")
VehicleDoor.create!(name: "4 Door")
VehicleDoor.create!(name: "5 Door")
printFinished()

printStarting("CREATING VEHICLE SIZE LIST")
VehicleSize.create!(name: "Small")
VehicleSize.create!(name: "Large")
printFinished()

printStarting("CREATING VEHICLE TYPE LIST")
VehicleType.create!(name: "Pickup")
VehicleType.create!(name: "SUV/Crossover")
VehicleType.create!(name: "SUV")
VehicleType.create!(name: "Crossover")
VehicleType.create!(name: "CUV")
VehicleType.create!(name: "Van")
VehicleType.create!(name: "Minivan")
VehicleType.create!(name: "Convertible")
VehicleType.create!(name: "Coupe")
VehicleType.create!(name: "Sedan")
VehicleType.create!(name: "Wagon")
VehicleType.create!(name: "Hatchback")
printFinished()

