printStarting("CREATING VEHICLE DOOR LIST")
VehicleDoor.create!(name: "2 Door")
VehicleDoor.create!(name: "3 Door")
VehicleDoor.create!(name: "4 Door")
VehicleDoor.create!(name: "5 Door")
VehicleDoor.create!(name: "6 Door")
printFinished()

printStarting("CREATING VEHICLE SIZE LIST")
VehicleSize.create!(name: "Small")
VehicleSize.create!(name: "Large")
printFinished()

printStarting("CREATING VEHICLE TYPE LIST")
VehicleType.create!(name: "Pickup")
VehicleType.create!(name: "SUV/Crossover")
VehicleType.create!(name: "SUV")
VehicleType.create!(name: "Crossover")
VehicleType.create!(name: "CUV")
VehicleType.create!(name: "Van")
VehicleType.create!(name: "Minivan")
VehicleType.create!(name: "Convertible")
VehicleType.create!(name: "Coupe")
VehicleType.create!(name: "Sedan")
VehicleType.create!(name: "Wagon")
VehicleType.create!(name: "Hatchback")
VehicleType.create!(name: "Pickup 5 1/2 ft bed")
VehicleType.create!(name: "Pickup 5 ft bed")
VehicleType.create!(name: "Pickup 6 1/3 ft bed")
VehicleType.create!(name: "Pickup 6 ft bed")
VehicleType.create!(name: "Pickup 8 ft bed")
VehicleType.create!(name: "Pickup-Long Bed")
VehicleType.create!(name: "Pickup-Short Bed")
VehicleType.create!(name: "Roadster")
VehicleType.create!(name: "SUV/Crossover/Pickup")
VehicleType.create!(name: "SUV/Crossover/Pickup 5 1/4 ft bed")
VehicleType.create!(name: "Van/Minivan")

printFinished()

